# Generated by Django 6.1 on 2026-08-08 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(auto_now_add=True)),
                ('planned_hours', models.PositiveIntegerField(default=2)),
                ('completed_hours', models.PositiveIntegerField(default=0)),
                ('completed_topic', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='planner.subject')),
            ],
        ),
    ]
